server:
  port: 8089
spring:
  datasource:
    name: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/casecader?useUnicode=true&characterEncoding=UTF8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 6468
mybatis:
  mapper-locations: classpath*:mapper/mysql/**/*.xml